name: MyJoinLeaveMessage
version: '${project.version}'
main: tech7.myjlmessage.my_joinleave_message.MyJoinLeaveMessage
api-version: 1.18
authors: [ Tech7 ]
description: A custom chat join and leave message plugin
commands:
  myjl:
    description: help command for MyJoinLeaveMessage plugin
    usage: /myjl
  myjl help:
    description: help command for MyJoinLeaveMessage plugin
    usage: /myjl help
  MyJoinLeaveMessage:
    description: help command for MyJoinLeaveMessage plugin
    usage: /MyJoinLeaveMessage
  MyJoinLeaveMessage help:
    description: help command for MyJoinLeaveMessage plugin
    usage: /MyJoinLeaveMessage help
  myjoin:
    description: command to change your join message
    usage: /myjoin
    permission: myjlmessage.myjoin
  myleave:
    description: command to change your leave message
    usage: /myleave
    permission: myjlmessage.myleave